module.exports = {
    PARAM_REQUIRE: 'PARAM_REQUIRE',
    DUPLICATE_USERNAME_OR_MAIL: 'DUPLICATE_USERNAME_OR_MAIL',
    SUCCESSS: 'SUCCESSS',
    FAILURE: 'FAILURE',
    CREATED_FAILURE: 'CREATED_FAILURE',
    PAGE_SIGE: 20,
    ACCESS_TIMEOUT: 2 * 60 * 60,
};
