module.exports = {
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE',
    ERROR: 'ERROR',
    NOT_FOUND: 'NOT_FOUND',
    CREATED_FAILURE: 'CREATED_FAILURE',
    UPDATE_ERROR: 'UPDATE_ERROR',
    PARAM_REQUIRE: 'PARAM_REQUIRE',
    UNAUTHORIZED: 'UNAUTHORIZED',
    DUPLICATE_USERNAME_OR_MAIL: 'DUPLICATE_USERNAME_OR_MAIL',
    WRONG_USERNAME_OR_PASSWORD: 'WRONG_USERNAME_OR_PASSWORD'
};
